alias td="cd ~/Desktop"
alias wk="cd ~/Desktop/workspace"
alias p='pnpm'
#alias dm="~/shell_scripts/dm.sh"
alias h="cd ~"
alias typora='/mnt/e/Program\ Files/Typora/Typora.exe'
alias _wk="cd /mnt/d"
alias l="ls -NX"
alias std="cd /mnt/d"
alias ani="~/shell_scripts/ani.sh"
alias tlc="cd ~/Desktop/workspace/learn-content"
alias joi="scp ./* root@ecs:/etc/nginx/cert/"
